[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[project]
name = "BehDat"
dynamic = ["version"]
requires-python = ">=3.11"
authors = [
    {name = "Lowell Bartlett", email = "bartlelo@ohsu.edu"}
]
maintainers = [
    {name = "Lowell Bartlett", email = "bartlelo@ohsu.edu"}
]
description = "A platform for Abbas lab processing and analysis of ephys, behavior, and video data"
readme = "README.md"
license = {text = "MIT License"}
keywords = ["pharmacology", "binding", "kinetics", "GUI", "HDF5"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License"    
]
dependencies = [
"numpy", 
"pandas",
"open-ephys-python-tools",
"pyside6",
"strenum",
"matplotlib",
"pybpod"
]


[tool.setuptools.packages.find]
where = ["src"]