function [FrameTime, FrameTrial] = find_first_frame(sessionData)

% This function finds the point in the behavior data that aligns with the first frame in the video data.
% The variable sessionfile should be a behavior data file generated by the
% bpod state machine r1, usually called SessionData.
% 
% INPUT:
%     sessionData - bpod behavior structure
% 
% OUTPUT:
%     FrameTime - Time relative to the start of the trial where video begins
%     FrameTrial - Trial num where video begins

EventCells = sessionData.RawEvents.Trial;
for trialno = 1:numel(EventCells)
    trialEvents = EventCells{trialno}.Events;
    if isfield(trialEvents, 'BNC1High') && isfield(trialEvents, 'BNC1Low')
        switch numel(trialEvents.BNC1High) - numel(trialEvents.BNC1Low)
            case 1      %More high timestamps
                BNCwidth = trialEvents.BNC1Low-trialEvents.BNC1High(1:end-1);
            case 0      %Equal number
                BNCwidth = abs(trialEvents.BNC1High - trialEvents.BNC1Low);
            case -1     %More low timestamps
                BNCwidth = trialEvents.BNC1High-trialEvents.BNC1Low(1:end-1);
        end
        if any(BNCwidth > 0.0165) % 50% duty cycle width indicates start of video recording, .0166 seconds at 30 fps
            firstFrame = find(BNCwidth > .0165, 1);
            FrameTime = trialEvents.BNC1High(firstFrame);
            FrameTrial = trialno;
            break
        end
    end
end
